spring.application.name=LogHub
springdoc.packages-to-scan=com.LogHub.features.clases.controllers

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d87o22jbc2fs73e62b1g-a.virginia-postgres.render.com/loghub_j48s
spring.datasource.username=loghub_user
spring.datasource.password=v5QncOpofPE99aUMncAodBanqtoi7SXe
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html